# Generated by Django 3.1.3 on 2021-05-23 09:10

import Apps.Usrs_Apps__Ak.Ak_User_Account.extensions.ProfileModelExt
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_profile', models.ImageField(blank=True, default='images/User/UserProfile/icon-avatar-default.png', upload_to=Apps.Usrs_Apps__Ak.Ak_User_Account.extensions.ProfileModelExt.RenameUserPhoto, validators=[Apps.Usrs_Apps__Ak.Ak_User_Account.extensions.ProfileModelExt.ImageSizaValidators], verbose_name='پروفایل')),
                ('delete_profile_checkbox', models.BooleanField(blank=True, default=False, verbose_name='حذف عکس کاربر')),
                ('gender_selection', models.CharField(blank=True, choices=[('MS', 'زن'), ('MR', 'مرد'), ('TG', 'دیگر')], max_length=2, verbose_name='انتخاب جنسیت')),
                ('postal_code', models.CharField(blank=True, help_text='کد پستی 10 رقمی میتواند شامل خط تیره (-) یا نباشد', max_length=20, validators=[Apps.Usrs_Apps__Ak.Ak_User_Account.extensions.ProfileModelExt.postal_code_validator], verbose_name='کد پستی')),
                ('phone_number', models.CharField(blank=True, help_text='شماره تماس باید 11 رقمی باشد و میتواند شامل صفر در ابتدای شماره نباشد', max_length=11, validators=[Apps.Usrs_Apps__Ak.Ak_User_Account.extensions.ProfileModelExt.phone_number_validator], verbose_name='شماره تماس')),
                ('location_first', models.CharField(blank=True, max_length=250, verbose_name='آدرس (1)')),
                ('NumberOfEmailsSentActivationLink', models.IntegerField(blank=True, default=0, verbose_name='تعداد ایمیل ارسالی فعالسازی حساب کاربری')),
                ('NumberOfEmailsSentToTheUser', models.IntegerField(blank=True, default=0, verbose_name='تعداد ایمیل های ارسال شده برای کاربر')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('msg', models.TextField(max_length=1500)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
