# Generated by Django 3.1.3 on 2021-05-23 10:57

import Apps.Usrs_Apps__Ak.Ak_User_Account.extensions.ProfileModelExt
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ak_User_Account', '0002_auto_20210523_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_profile',
            field=models.ImageField(blank=True, default='icon-avatar-default.png', upload_to=Apps.Usrs_Apps__Ak.Ak_User_Account.extensions.ProfileModelExt.RenameUserPhoto, validators=[Apps.Usrs_Apps__Ak.Ak_User_Account.extensions.ProfileModelExt.ImageSizaValidators], verbose_name='پروفایل'),
        ),
    ]
