# Generated by Django 3.1.3 on 2021-05-23 09:10

import Apps.SiteSettings_Apps__Ak.SiteSettings.extensions.SiteSettingsExt
import Apps.Usrs_Apps__Ak.Ak_User_Account.Validation_User_Input.FormValidation
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SiteSettingName', models.CharField(max_length=35)),
                ('BlackLogoSiteHeader', models.ImageField(upload_to=Apps.SiteSettings_Apps__Ak.SiteSettings.extensions.SiteSettingsExt.RenameTheLogoIcon, validators=[Apps.SiteSettings_Apps__Ak.SiteSettings.extensions.SiteSettingsExt.CheckLogo], verbose_name='لوگو هدر سایت')),
                ('WhiteLogoSiteFooter', models.ImageField(upload_to=Apps.SiteSettings_Apps__Ak.SiteSettings.extensions.SiteSettingsExt.RenameTheLogoIcon, validators=[Apps.SiteSettings_Apps__Ak.SiteSettings.extensions.SiteSettingsExt.CheckLogo], verbose_name='لوگو فوتر سایت')),
                ('CopyrightText', models.CharField(max_length=70, verbose_name='متن کپی رایت')),
                ('CompanyAddress', models.CharField(max_length=60, verbose_name='آدرس شرکت')),
                ('EmailSupportSite', models.EmailField(max_length=40, validators=[Apps.Usrs_Apps__Ak.Ak_User_Account.Validation_User_Input.FormValidation.EmailValidation], verbose_name='آدرس ایمیل پشتیبانی سایت')),
                ('SiteSupportContactNumber', models.CharField(max_length=15, validators=[Apps.SiteSettings_Apps__Ak.SiteSettings.extensions.SiteSettingsExt.CheckThePreCodeContactPhone], verbose_name='شماره تلفن پشتیبانی سایت')),
                ('ShortDescriptionFooter', models.CharField(max_length=100, verbose_name='توضیحات کوتاه سایت در پاورقی')),
                ('InstagramSite', models.URLField(validators=[Apps.SiteSettings_Apps__Ak.SiteSettings.extensions.SiteSettingsExt.CheckInstagramUrl], verbose_name='آدرس اینستاگرام سایت')),
                ('YoutubeSite', models.URLField(validators=[Apps.SiteSettings_Apps__Ak.SiteSettings.extensions.SiteSettingsExt.CheckYoutubeUrl], verbose_name='آدرس کانال یوتیوب سایت')),
                ('TelegramSite', models.URLField(validators=[Apps.SiteSettings_Apps__Ak.SiteSettings.extensions.SiteSettingsExt.CheckTelegramUrl], verbose_name='آدرس کانال تلگرام سایت')),
                ('FacebookSite', models.URLField(validators=[Apps.SiteSettings_Apps__Ak.SiteSettings.extensions.SiteSettingsExt.CheckFacebookUrl], verbose_name='آدرس فیسبوک سایت')),
                ('TwitterSite', models.URLField(validators=[Apps.SiteSettings_Apps__Ak.SiteSettings.extensions.SiteSettingsExt.CheckTwitterUrl], verbose_name='آدرس توییتر سایت')),
            ],
        ),
        migrations.CreateModel(
            name='SelectSiteSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SelectBox', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SiteSettings.sitesettings', verbose_name='انتخاب تنظمیات سایت')),
            ],
        ),
        migrations.CreateModel(
            name='BrandPhotoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BrandName', models.CharField(max_length=35, unique=True)),
                ('BrandPhoto', models.ImageField(upload_to=Apps.SiteSettings_Apps__Ak.SiteSettings.extensions.SiteSettingsExt.RenameTheBrandPhoto, validators=[Apps.SiteSettings_Apps__Ak.SiteSettings.extensions.SiteSettingsExt.CheckBrandPhoto])),
                ('SiteSetting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SiteSettings.sitesettings')),
            ],
        ),
    ]
