# Generated by Django 3.1.3 on 2021-05-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSettings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='default_user_photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس پیشفرض کاربران فاقد نمایه'),
        ),
    ]
