# Generated by Django 3.1.3 on 2021-05-23 09:10

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customize_Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_color', models.CharField(choices=[('PR', 'بنفش'), ('GR', 'سبز'), ('RD', 'قرمز'), ('BL', 'آبی'), ('OG', 'نارنجی'), ('BC', 'مشکی')], default='BL', max_length=2, verbose_name='رنگ منو')),
                ('theme_color', models.CharField(choices=[('LT', 'روشن'), ('DK', 'تاریک'), ('ST', 'نیمه روشن')], default='LT', max_length=2, verbose_name='رنگ تم')),
                ('menu_mode', models.BooleanField(default=False, verbose_name='حالت منو')),
                ('header_color', models.CharField(choices=[('WT', 'سفید'), ('PR', 'بنفش'), ('GR', 'سبز'), ('RD', 'قرمز'), ('BL', 'آبی'), ('OG', 'نارنجی'), ('BC', 'مشکی')], default='WT', max_length=2, verbose_name='رنگ سربرگ')),
                ('header_mode', models.CharField(choices=[('HN', 'مخفی'), ('FD', 'ثابت'), ('SG', 'چسبیده'), ('FG', 'شناور')], default='FG', max_length=2, verbose_name='حالت سربرگ')),
                ('footer_mode', models.CharField(choices=[('HN', 'مخفی'), ('FD', 'ثابت'), ('SG', 'چسبیده')], default='FD', max_length=2, verbose_name='حالت پاورقی')),
                ('flash_navigation_mode', models.BooleanField(default=True, verbose_name='حالت فلش پیمایش صفحه')),
            ],
        ),
        migrations.CreateModel(
            name='Email_Management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('html_content', ckeditor.fields.RichTextField(max_length=2800)),
                ('send_date', models.DateTimeField(blank=True, null=True)),
                ('number_of_submissions', models.BigIntegerField(blank=True, null=True)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
