# Generated by Django 3.1.3 on 2021-05-23 09:10

import ckeditor.fields
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/Product-Brand/')),
                ('name', models.CharField(max_length=70)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('pay_time', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('Postage', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=40, verbose_name='نام دسته بندی')),
                ('slug', models.SlugField(allow_unicode=True, default=None)),
                ('category_photo', models.ImageField(blank=True, default=None, upload_to='images/Product-Category/', verbose_name='تصویر دسته بندی')),
                ('category_making_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Home_Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('text', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Post_Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=None, verbose_name='نشانی اینترنتی')),
                ('photo', models.ImageField(upload_to='images/Product-Photos/', verbose_name='تصویر محصول')),
                ('name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('short_description', ckeditor.fields.RichTextField(max_length=300, verbose_name='توضیحات کوتاه محصول')),
                ('further_details', ckeditor.fields.RichTextField(max_length=3000, verbose_name='توضیحات کامل محصول')),
                ('attributes', django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='ویژگی های محصول')),
                ('discounted_price', models.FloatField(blank=True, default=None, verbose_name='قیمت با تخفیف محصول')),
                ('discount_percent', models.IntegerField(blank=True, default=None, verbose_name='درصد تخفیف')),
                ('final_price', models.FloatField(verbose_name='قیمت نهایی محصول')),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('production_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد محصول')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('inventory', models.IntegerField(verbose_name='تعداد موجود')),
                ('special_offer', models.BooleanField(default=False, verbose_name='پیشنهاد ویژه')),
                ('sold', models.IntegerField(blank=True, default=0, verbose_name='تعداد فروخته شده')),
                ('status', models.CharField(choices=[('NS', '-------'), ('PB', 'انتشار'), ('AC', 'بایگانی')], default='NS', max_length=2, verbose_name='وضعیت انتشار')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product_Apps__Ak.brand_model')),
                ('category', models.ManyToManyField(help_text='لطفا حداقل 5 دسته بندی برای محصول خود انتخاب کنید', to='Product_Apps__Ak.Category_Product', verbose_name='انتخاب دسته بندی محصول')),
                ('slider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product_Apps__Ak.home_slider')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=35, verbose_name='نام برچسب')),
                ('tag_making_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slider_Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/Slider-Photos/')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Product_Apps__Ak.post_products')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان ارسال نظر')),
                ('star', models.IntegerField(choices=[(1, '⭐'), (2, '⭐ ⭐'), (3, '⭐ ⭐ ⭐'), (4, '⭐ ⭐ ⭐ ⭐'), (5, '⭐ ⭐ ⭐ ⭐ ⭐')], default=None, verbose_name='امتیاز محصول')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product_Apps__Ak.post_products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Visit_Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product_Apps__Ak.post_products')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_code', models.CharField(max_length=20)),
                ('color_name', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product_Apps__Ak.post_products')),
            ],
        ),
        migrations.AddField(
            model_name='post_products',
            name='tag',
            field=models.ManyToManyField(to='Product_Apps__Ak.Product_Tags', verbose_name='انتخاب برچسب های محصول'),
        ),
        migrations.CreateModel(
            name='More_Product_Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/More-Product-Photos/', verbose_name='تصویر های بیشتر محصول')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product_Apps__Ak.post_products')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(blank=True, default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product_Apps__Ak.post_products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('total', models.FloatField(blank=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product_Apps__Ak.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product_Apps__Ak.post_products')),
            ],
        ),
    ]
