# Generated by Django 3.1.3 on 2021-05-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Apps__Ak', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_products',
            name='special_offer',
            field=models.BooleanField(blank=True, default=False, verbose_name='پیشنهاد ویژه'),
        ),
    ]
