# Generated by Django 3.1.3 on 2021-05-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Apps__Ak', '0002_auto_20210523_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_products',
            name='discount_percent',
            field=models.IntegerField(blank=True, default=0, verbose_name='درصد تخفیف'),
        ),
    ]
