# Generated by Django 3.1.3 on 2021-05-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Apps__Ak', '0004_auto_20210523_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_products',
            name='attributes',
            field=models.JSONField(default=dict, verbose_name='ویژگی های محصول'),
        ),
    ]
